server:
  port: 8085
spring:
  application:
    name: shortest-path-service
  cloud:
    zookeeper:
      connect-string: zookeeper:2181
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
