server:
  port: 8087
spring:
  application:
    name: ranker-service
  cloud:
    zookeeper:
      connect-string: zookeeper:2181
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  metrics:
    tags:
      application: ${spring.application.name}
